#!/usr/bin/env sh
# boominit.sh — bootstrap this dotfiles repo on a fresh machine. One command:
#   git clone <repo> && ./<repo>/boominit.sh
# Installs boom if missing, points it here, and applies. Generated by `boom init`.
set -eu
REPO="$(cd "$(dirname "$0")" && pwd)"
if ! command -v boom > /dev/null 2>&1; then
  echo "boominit: installing boom…"
  curl -fsSL https://raw.githubusercontent.com/alxjrvs/boom/main/install.sh | sh
fi
boom init "$REPO"
boom apply "$@"
