#!/usr/bin/env sh
# botuinit.sh — bootstrap this dotfiles repo on a fresh machine. One command:
#   git clone <repo> && ./<repo>/botuinit.sh
# Installs botu if missing, points it at this repo, and applies. Generated by
# `botu init` — do not edit by hand (re-run `botu init` to refresh).
set -eu
REPO="$(cd "$(dirname "$0")" && pwd)"
if ! command -v botu > /dev/null 2>&1; then
  echo "botuinit: installing botu…"
  curl -fsSL https://raw.githubusercontent.com/alxjrvs/botu/main/install.sh | sh
fi
botu init "$REPO"
botu apply "$@"
