tap "supabase/tap"
# tap "wix/brew"          # iOS simulator tools
brew "mise"
# brew "bundletool"      # Android only
# brew "cmake"           # C/C++ only
brew "libsodium"
# brew "fastlane"        # iOS CI only
brew "flyctl"
brew "fzf"
brew "gh"
brew "git-delta"
brew "lazygit"
brew "bat"
brew "difftastic"
brew "gitleaks"
brew "age"
brew "dust"
brew "eza"
brew "glow"
brew "bun"
brew "fd"
brew "jq"
brew "yq"
brew "neovim"
brew "unbound", restart_service: true
brew "gnutls"
brew "gnupg"
brew "krb5"
brew "tmux"
brew "overmind"
brew "redis", restart_service: true
brew "direnv"
brew "ripgrep"
brew "tealdeer"
# brew "watchman"        # React Native only
brew "zoxide"
brew "sheldon"
brew "shfmt"
brew "starship"
brew "supabase/tap/supabase"
# brew "wix/brew/applesimutils"  # iOS simulator
cask "1password-cli"
cask "1password"
cask "claude"
cask "devutils"
cask "discord"
cask "docker-desktop"
cask "font-fira-code-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "ngrok"
cask "notunes"
cask "rectangle"
cask "slack"
cask "tuple"
# cask "zulu@17"          # Java/Android only
