tap 'homebrew/cask-fonts'

cask 'font-fira-code'
cask 'visual-studio-code'
cask 'google-chrome'
cask 'slack'
cask 'discord'
cask '1password'
cask 'rectangle'
cask 'docker'

brew 'postgresql'
brew 'asdf'
brew 'gh'
brew 'gpg'
